name: Jira Exporter Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *' # This sets the workflow to run every hour.

jobs:
  run-integration:
    runs-on: ubuntu-latest  # This job will run on the latest Ubuntu environment.
    timeout-minutes: 30  # Job will be killed if it runs for more than 30 minutes.

    steps:
      # First step uses the port-labs/ocean-sail GitHub Action.
      - uses: port-labs/ocean-sail@v1
        with:
          type: 'jira'  # Specify the type of integration (Jira in this case)
          port_client_id: ${{ secrets.OCEAN__PORT__CLIENT_ID }}  # Secret containing Port Client ID
          port_client_secret: ${{ secrets.OCEAN__PORT__CLIENT_SECRET }}  # Secret containing Port Client Secret
          port_base_url: https://api.getport.io  # Port API URL for EU region (adjust if necessary for US)
          config: |
            jira_host: ${{ secrets.OCEAN__INTEGRATION__CONFIG__JIRA_HOST }}  # Secret for Jira URL
            atlassian_user_email: ${{ secrets.OCEAN__INTEGRATION__CONFIG__ATLASSIAN_USER_EMAIL }}  # Secret for Jira user email
            atlassian_user_token: ${{ secrets.OCEAN__INTEGRATION__CONFIG__ATLASSIAN_USER_TOKEN }}  # Secret for Jira API token
